title: Your Project Title
description: Documentation Site
url: https://yourusername.github.io
baseurl: "/your-repo" # Adjust if necessary
theme: minima
markdown: kramdown

# Jekyll Configuration
plugins:
  - jekyll-seo-tag
